# Configuraci�n de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/datascience_db
spring.datasource.username=nocountry
spring.datasource.password=1234

# Configuraci�n de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuraci�n existente del proyecto (para el modelo Python)
ds.api.url=http://localhost:5000/predict

# Opcional para debug
logging.level.org.hibernate.SQL=DEBUG