### Prueba de Predicción de Vuelo
POST http://localhost:8080/api/v1/flights/predict
Content-Type: application/json

{
  "aerolinea": "Aeromexico",
  "origen": "MEX",
  "destino": "LAX",
  "fechaPartida": "2025-11-10T14:30:00",
  "distanciaKm": 2500
}